core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    
    AddCouponView,
    RequestRefundView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

market/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse


CATEGORY_CHOICES = (
    ('TV', 'Television'),
    ('AU', 'Audio'),
    ('AC', 'Air conditioner'),
    ('CM', 'Cameras'),
    ('AU', 'Refrigerators'),
    ('GC', 'Gas cookers'),
    ('FZ', 'Freezers'),
    ('WM', 'Washing machine'),
    ('FN', 'Fans'),
    ('KA', 'Kitchen Appliances'),
    
)




ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    discount_price = models.IntegerField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/home.html
{% extends "base.html" %}

{% block content %}




<!-- Featured Start -->
<div class="container-fluid pt-5">
  <div class="row px-xl-5 pb-3">
      <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
          <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
              <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
              <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
          </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
          <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
              <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
              <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
          </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
          <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
              <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
              <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
          </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
          <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
              <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
              <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
          </div>
      </div>
  </div>
</div>
<!-- Featured End -->


<!-- Categories Start -->
<div class="container-fluid pt-5">
  <div class="row px-xl-5 pb-3">
      <div class="col-lg-4 col-md-6 pb-1">
          <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
              <p class="text-right">Brand</p>
              <a href="" class="cat-img position-relative overflow-hidden mb-3">
                  <img class="img-fluid" src="img/cat-1.jpg" alt="">
              </a>
              <h5 class="font-weight-semi-bold m-0">Samsung</h5>
          </div>
      </div>
      <div class="col-lg-4 col-md-6 pb-1">
          <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
              <p class="text-right">Brand</p>
              <a href="" class="cat-img position-relative overflow-hidden mb-3">
                  <img class="img-fluid" src="img/cat-2.jpg" alt="">
              </a>
              <h5 class="font-weight-semi-bold m-0">Panasonic</h5>
          </div>
      </div>
      <div class="col-lg-4 col-md-6 pb-1">
          <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
              <p class="text-right">Brand</p>
              <a href="" class="cat-img position-relative overflow-hidden mb-3">
                  <img class="img-fluid" src="img/cat-3.jpg" alt="">
              </a>
              <h5 class="font-weight-semi-bold m-0">Scanfrost</h5>
          </div>
      </div>
      <div class="col-lg-4 col-md-6 pb-1">
          <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
              <p class="text-right">Brand</p>
              <a href="" class="cat-img position-relative overflow-hidden mb-3">
                  <img class="img-fluid" src="img/cat-4.jpg" alt="">
              </a>
              <h5 class="font-weight-semi-bold m-0">Toshiba</h5>
          </div>
      </div>
      <div class="col-lg-4 col-md-6 pb-1">
          <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
              <p class="text-right">Brand</p>
              <a href="" class="cat-img position-relative overflow-hidden mb-3">
                  <img class="img-fluid" src="img/cat-5.jpg" alt="">
              </a>
              <h5 class="font-weight-semi-bold m-0">TCL</h5>
          </div>
      </div>
      <div class="col-lg-4 col-md-6 pb-1">
          <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
              <p class="text-right">Brand</p>
              <a href="" class="cat-img position-relative overflow-hidden mb-3">
                  <img class="img-fluid" src="img/cat-6.jpg" alt="">
              </a>
              <h5 class="font-weight-semi-bold m-0">Aeon</h5>
          </div>
      </div>
  </div>
</div>
<!-- Categories End -->


<!-- Offer Start 
<div class="container-fluid offer pt-5">
  <div class="row px-xl-5">
      <div class="col-md-6 pb-4">
          <div class="position-relative bg-secondary text-center text-md-right text-white mb-2 py-5 px-5">
              <img src="img/offer-1.png" alt="">
              <div class="position-relative" style="z-index: 1;">
                  <h5 class="text-uppercase text-primary mb-3">20% off the all order</h5>
                  <h1 class="mb-4 font-weight-semi-bold">Spring Collection</h1>
                  <a href="" class="btn btn-outline-primary py-md-2 px-md-3">Shop Now</a>
              </div>
          </div>
      </div>
      <div class="col-md-6 pb-4">
          <div class="position-relative bg-secondary text-center text-md-left text-white mb-2 py-5 px-5">
              <img src="img/offer-2.png" alt="">
              <div class="position-relative" style="z-index: 1;">
                  <h5 class="text-uppercase text-primary mb-3">20% off the all order</h5>
                  <h1 class="mb-4 font-weight-semi-bold">Winter Collection</h1>
                  <a href="" class="btn btn-outline-primary py-md-2 px-md-3">Shop Now</a>
              </div>
          </div>
      </div>
  </div>
</div>
-->


<!-- Products Start -->
<main>
    <section class="text-center mb-4">
        <h2 class="section-title px-5 mb-5 mt-5"><span class="px-2">Hot deals</span></h2>
        <div class="row wow fadeIn">
    
          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">
    
            <div class="card ml-5">
    
              <div class="view overlay">
                <span style="color:white; background-color:rgb(202, 27, 27); float: right; padding: 2px 4px; border-radius: 5px;">NEW</span>
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
    
              <div class="card-body text-center">
                <a href="">
                  <h6 style="color: #1c8080; border-radius: 5px; padding: 2px;">{{ item.get_category_display }}</h6>
                </a>
                <hr>
                <h5 class="mb-5">
                  
                    <a href="{{ item.get_absolute_url }}" style="text-decoration: none;">{{ item.title }}
                      
                    </a>
                  
                </h5>
    
                <h6>
                  
                  {% if item.discount_price %}
                  NGN <b>{{ item.discount_price }}</b> </h6>
                  
                  <small><del>NGN {{ item.price }}</del></small>
                 
                  {% else %}
                  <h6>{{ item.price }}</h6>
                  
                  {% endif %}
                  
                
    
              </div>
    
              <div class="card-footer d-flex justify-content-between bg-light border">
                <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
            </div>
    
            </div>
    
          </div>
          {% endfor %}
        </div>
    
      </section>
    
    
</main>





<!--
  <main>
    <div class="container">

      
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        
        <span class="navbar-brand">Categories:</span>

       
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        
        <div class="collapse navbar-collapse" id="basicExampleNav">

          
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
         

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        

      </nav>
      

      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
     

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

-->
{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}

{% load static %}

<!-- Topbar Start -->
<div class="container-fluid">
  <div class="row bg-secondary py-2 px-xl-5">
      <div class="col-lg-6 d-none d-lg-block">
          <div class="d-inline-flex align-items-center">
              <a class="text-dark" href="">FAQs</a>
              <span class="text-muted px-2">|</span>
              <a class="text-dark" href="">Help</a>
              <span class="text-muted px-2">|</span>
              <a class="text-dark" href="">Support</a>
          </div>
      </div>
      <div class="col-lg-6 text-center text-lg-right">
          <div class="d-inline-flex align-items-center">
              <a class="text-dark px-2" href="">
                  <i class="fab fa-facebook-f"></i>
              </a>
              <a class="text-dark px-2" href="">
                  <i class="fab fa-twitter"></i>
              </a>
              <a class="text-dark px-2" href="">
                  <i class="fab fa-linkedin-in"></i>
              </a>
              <a class="text-dark px-2" href="">
                  <i class="fab fa-instagram"></i>
              </a>
              <a class="text-dark pl-2" href="">
                  <i class="fab fa-youtube"></i>
              </a>
          </div>
      </div>
  </div>
  <div class="row align-items-center py-3 px-xl-5">
      <div class="col-lg-3 d-none d-lg-block">
          <a href="" class="text-decoration-none">
              <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
          </a>
      </div>
      <div class="col-lg-6 col-6 text-left">
          <form action="">
              <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for products">
                  <div class="input-group-append">
                      <span class="input-group-text bg-transparent text-primary">
                          <i class="fa fa-search"></i>
                      </span>
                  </div>
              </div>
          </form>
      </div>
      <div class="col-lg-3 col-6 text-right">
          <a href="" class="btn border">
              <i class="fas fa-heart text-primary"></i>
              <span class="badge">0</span>
          </a>
          <a href="" class="btn border">
              <i class="fas fa-shopping-cart text-primary"></i>
              <span class="badge">0</span>
          </a>
      </div>
  </div>
</div>
<!-- Topbar End -->


<!-- Navbar Start -->
<div class="container-fluid mb-5">
  <div class="row border-top px-xl-5">
      <div class="col-lg-3 d-none d-lg-block">
          <a class="btn shadow-none d-flex align-items-center justify-content-between text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="background-color: #3e81cd; color:white; height: 65px; margin-top: -1px; padding: 0 30px;">
              <h6 class="m-0", style="color:white;">Categories</h6>
              <i class="fa fa-angle-down text-dark"></i>
          </a>
          <nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
              <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                  <div class="nav-item dropdown">
                      <a href="#" class="nav-link" data-toggle="dropdown">Air conditioners <i class="fa fa-angle-down float-right mt-1"></i></a>
                      <div class="dropdown-menu position-absolute bg-secondary border-0 rounded-0 w-100 m-0">
                          <a href="" class="dropdown-item">Split AC</a>
                          <a href="" class="dropdown-item">Inverter AC</a>
                          <a href="" class="dropdown-item">Standing AC</a>
                          <a href="" class="dropdown-item">Air purifiers and coolers</a>
                      </div>
                      
                  </div>
                  
                  <a href="" class="nav-item nav-link">Audio</a>
                  <a href="" class="nav-item nav-link">Cameras</a>
                  <a href="" class="nav-item nav-link">Fans</a>
                  <a href="" class="nav-item nav-link">Freezers</a>
                  <a href="" class="nav-item nav-link">Gas cookers</a>
                  <a href="" class="nav-item nav-link">Homeware</a>
                  <a href="" class="nav-item nav-link">Kitchen Appliances</a>
                  <a href="" class="nav-item nav-link">Refrigerators</a>
                  <a href="" class="nav-item nav-link">Television</a>
                  <a href="" class="nav-item nav-link">Washing machine</a>
                  
              </div>
          </nav>
      </div>
      <div class="col-lg-9">
          <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
              <a href="" class="text-decoration-none d-block d-lg-none">
                  <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
              </a>
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                  <div class="navbar-nav mr-auto py-0">
                      <a href="index.html" class="nav-item nav-link active">Home</a>
                      
                      <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Air conditioner</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="cart.html" class="dropdown-item">Split AC</a>
                            <a href="checkout.html" class="dropdown-item">Inverter AC</a>
                            <a href="checkout.html" class="dropdown-item">Standing AC</a>
                            <a href="checkout.html" class="dropdown-item">Air purifiers and coolers</a>
                        </div>
                      </div>
                      <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Audio</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="cart.html" class="dropdown-item">Media players</a>
                            <a href="checkout.html" class="dropdown-item">Headphones</a>
                            <a href="checkout.html" class="dropdown-item">Speakers</a>
                            <a href="checkout.html" class="dropdown-item">Home theatre systems and sound bars</a>
                        </div>
                      </div>
                      <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Kitchen Appliances</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="cart.html" class="dropdown-item">Gas cookers</a>
                            <a href="checkout.html" class="dropdown-item">Freezers</a>
                            <a href="checkout.html" class="dropdown-item">Refrigerators</a>
                            
                        </div>
                      </div>
                      <a href="index.html" class="nav-item nav-link">Camera</a>
                      <a href="index.html" class="nav-item nav-link">Fans</a>
                      <a href="index.html" class="nav-item nav-link">Television</a>
                  </div>
                  <div class="navbar-nav ml-auto py-0">
                      <a href="" class="nav-item nav-link">Login</a>
                      <a href="" class="nav-item nav-link">Register</a>
                  </div>
              </div>
          </nav>
          <div id="header-carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                  <div class="carousel-item active" style="height: 410px;">
                      <img class="img-fluid" src="{% static 'img/sony1.jpg' %}" alt="Image">
                      <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                          <div class="p-3" style="max-width: 700px;">
                              <h4 class="text-light text-uppercase font-weight-medium mb-3">Prompt delivery</h4>
                              <h3 class="display-4 text-white font-weight-semi-bold mb-4">Genuine Electronics</h3>
                              <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                          </div>
                      </div>
                  </div>
                  <div class="carousel-item" style="height: 410px;">
                      <img class="img-fluid" src="{% static 'img/scanfrost1.jpg' %}" alt="Image">
                      <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                          <div class="p-3" style="max-width: 700px;">
                              <h4 class="text-light text-uppercase font-weight-medium mb-3">Customer satisfaction</h4>
                              <h3 class="display-4 text-white font-weight-semi-bold mb-4">Affordable Price</h3>
                              <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                          </div>
                      </div>
                  </div>
              </div>
              <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
                  <div class="btn btn-dark" style="width: 45px; height: 45px;">
                      <span class="carousel-control-prev-icon mb-n2"></span>
                  </div>
              </a>
              <a class="carousel-control-next" href="#header-carousel" data-slide="next">
                  <div class="btn btn-dark" style="width: 45px; height: 45px;">
                      <span class="carousel-control-next-icon mb-n2"></span>
                  </div>
              </a>
          </div>
      </div>
  </div>
</div>
<!-- Navbar End -->






















<!--

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">DJe-commerce</strong>
      </a>

     
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

       
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>
-->

  